name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  validate-and-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install jsonschema

      - name: Validate manifest
        run: |
          python src/aip_runner/cli.py validate examples/article_pipeline.aip.json

      - name: Demo run (no LLM)
        run: |
          python src/aip_runner/cli.py run examples/article_pipeline.aip.json
