name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-and-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install deps (and package if available)
        run: |
          set -e
          python -m pip install --upgrade pip
          pip install jsonschema
          if [ -f "pyproject.toml" ]; then
            echo "pyproject.toml found → installing package (editable)"
            pip install -e .
          else
            echo "pyproject.toml not found → will use 'python src/aip_runner/cli.py'"
          fi

      - name: Detect manifest path
        id: manifest
        run: |
          set -e
          if [ -f "examples/article_pipeline.aip.json" ]; then
            echo "manifest=examples/article_pipeline.aip.json" >> "$GITHUB_OUTPUT"
          elif [ -f "примеры/article_pipeline.aip.json" ]; then
            echo "manifest=примеры/article_pipeline.aip.json" >> "$GITHUB_OUTPUT"
          else
            echo "::error::Manifest file not found. Expected at 'examples/article_pipeline.aip.json' or 'примеры/article_pipeline.aip.json'."
            exit 1
          fi

      - name: Detect CLI entrypoint
        id: cli
        run: |
          set -e
          if command -v aip-runner >/dev/null 2>&1; then
            echo "cli=aip-runner" >> "$GITHUB_OUTPUT"
          else
            echo "cli=python src/aip_runner/cli.py" >> "$GITHUB_OUTPUT"
          fi

      - name: Validate manifest
        run: ${{ steps.cli.outputs.cli }} validate "${{ steps.manifest.outputs.manifest }}"

      - name: Demo run (no LLM)
        run: ${{ steps.cli.outputs.cli }} run "${{ steps.manifest.outputs.manifest }}"

      # --- Artifacts check ---
      - name: Clean artifacts dir
        run: rm -rf artifacts || true

      - name: Demo run (with artifacts)
        run: ${{ steps.cli.outputs.cli }} run "${{ steps.manifest.outputs.manifest }}"

      - name: Check artifact exists
        run: |
          set -e
          test -f artifacts/article.txt || (echo "::error::artifacts/article.txt not found"; ls -la artifacts || true; exit 1)
          echo "OK: artifacts/article.txt created"

      # --- MCP demo ---
      - name: Validate manifest (MCP demo)
        run: ${{ steps.cli.outputs.cli }} validate examples/mcp_read.aip.json

      - name: Demo run (MCP demo, no real MCP)
        run: ${{ steps.cli.outputs.cli }} run examples/mcp_read.aip.json

      - name: Demo run (MCP demo with env config)
        env:
          AIP_MCP_SERVERS: '{"filesystem":{"cmd":"mcp-filesystem --root ./","transport":"stdio"}}'
        run: ${{ steps.cli.outputs.cli }} --mcp run examples/mcp_read.aip.json
