name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-and-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (and package if available)
        run: |
          set -e
          python -m pip install --upgrade pip
          pip install jsonschema
          if [ -f "pyproject.toml" ]; then
            echo "pyproject.toml found → installing package (editable)"
            pip install -e .
          else
            echo "pyproject.toml not found → will use 'python src/aip_runner/cli.py'"
          fi

      - name: Detect manifest path
        id: manifest
        run: |
          set -e
          if [ -f "examples/article_pipeline.aip.json" ]; then
            echo "manifest=examples/article_pipeline.aip.json" >> "$GITHUB_OUTPUT"
            echo "Using manifest: examples/article_pipeline.aip.json"
          elif [ -f "примеры/article_pipeline.aip.json" ]; then
            echo "manifest=примеры/article_pipeline.aip.json" >> "$GITHUB_OUTPUT"
            echo "Using manifest: примеры/article_pipeline.aip.json"
          else
            echo "::error::Manifest file not found. Expected at 'examples/article_pipeline.aip.json' or 'примеры/article_pipeline.aip.json'."
            exit 1
          fi

      - name: Detect CLI entrypoint
        id: cli
        run: |
          set -e
          if command -v aip-runner >/dev/null 2>&1; then
            echo "cli=aip-runner" >> "$GITHUB_OUTPUT"
            echo "Will use CLI: aip-runner"
          else
            echo "cli=python src/aip_runner/cli.py" >> "$GITHUB_OUTPUT"
            echo "Console script not found → fallback to 'python src/aip_runner/cli.py'"
          fi

      - name: Validate manifest
        run: |
          set -e
          echo "CLI: ${{ steps.cli.outputs.cli }}"
          echo "MANIFEST: ${{ steps.manifest.outputs.manifest }}"
          ${{ steps.cli.outputs.cli }} validate "${{ steps.manifest.outputs.manifest }}"

      - name: Demo run (no LLM)
        run: |
          set -e
          ${{ steps.cli.outputs.cli }} run "${{ steps.manifest.outputs.manifest }}"
